In [429]:
import json
import requests
import pandas as pd
import csv

url = 'https://merolagani.com/handlers/webrequesthandler.ashx?type=get_company_graph&symbol=SRBL&dateRange=300'
f = requests.get(url)
_f=f.text

In [430]:
json_acceptable_string = _f.replace("'", "\"")
d = json.loads(json_acceptable_string)

In [431]:
data = d.get('quotes')

In [432]:
open = []
high =[]
low =[]
close = []
volume =[]
rsi =[]
date = []



for i in range(len(data)):
   
    op = data[i].get('open')
    open.append(op)
    
    hi = data[i].get('high')
    high.append(hi)
    
    lo = data[i].get('low')
    low.append(lo)
   
    clo = data[i].get('close')
    close.append(clo)
    
    vol = data[i].get('volume')
    volume.append(vol)
    
    rs = data[i].get('rsi')
    rsi.append(rs)
    
    dt = data[i].get('date')
    date.append(dt)

In [433]:
df = pd.DataFrame({'Date':date,'Open':open,'Close':close,'High':high,'Low':low,'Volume':volume,'RSI':rsi})

In [434]:
df

            Date   Open  Close   High    Low   Volume    RSI
0     01/30/2002  398.0  230.0  231.0  227.0   9526.0   0.00
1     11/03/2009  230.0  450.0  499.0  441.0   1180.0   0.00
2     11/04/2009  450.0  431.0  441.0  422.0   9010.0   0.00
3     11/05/2009  431.0  455.0  455.0  410.0   5860.0   0.00
4     11/08/2009  455.0  455.0  460.0  440.0  10360.0   0.00
5     11/09/2009  455.0  448.0  460.0  446.0   7680.0   0.00
6     11/10/2009  448.0  438.0  456.0  437.0   6350.0   0.00
7     11/11/2009  438.0  432.0  445.0  428.0   5530.0   0.00
8     11/12/2009  432.0  430.0  430.0  404.0   5210.0   0.00
9     11/15/2009  430.0  425.0  434.0  419.0   4350.0   0.00
10    11/16/2009  425.0  410.0  420.0  409.0   6410.0   0.00
11    11/17/2009  410.0  410.0  412.0  400.0   3860.0   0.00
12    11/18/2009  410.0  411.0  415.0  402.0   5160.0   0.00
13    11/19/2009  411.0  413.0  420.0  399.0   3440.0   0.00
14    11/22/2009  413.0  416.0  418.0  410.0   2410.0  51.57
15    11/23/2009  416.0  400.0  412.0  398.0   3120.0  49.78
16    11/24/2009  400.0  390.0  399.0  390.0   5000.0  48.64
17    11/25/2009  390.0  392.0  396.0  380.0   3330.0  48.89
18    11/26/2009  392.0  385.0  394.0  383.0   4560.0  48.00
19    11/30/2009  385.0  366.0  392.0  361.0   3590.0  45.59
20    12/01/2009  366.0  363.0  365.0  351.0   3730.0  45.20
21    12/03/2009  363.0  355.0  362.0  348.0   3900.0  44.13
22    12/06/2009  355.0  367.0  367.0  349.0   5990.0  46.20
23    12/07/2009  367.0  402.0  403.0  349.0   3670.0  51.80
24    12/08/2009  402.0  416.0  422.0  400.0   3810.0  53.86
25    12/09/2009  416.0  421.0  425.0  405.0   9850.0  54.61
26    12/10/2009  421.0  429.0  437.0  419.0  11400.0  55.85
27    12/13/2009  429.0  420.0  435.0  410.0   2490.0  54.07
28    12/14/2009  420.0  429.0  433.0  422.0   3630.0  55.59
29    12/15/2009  429.0  420.0  431.0  400.0   4080.0  53.67
...          ...    ...    ...    ...    ...      ...    ...
2160  05/08/2019  255.0  256.0  260.0  254.0  10344.0  57.13
2161  05/09/2019  255.0  253.0  255.0  252.0  12919.0  54.35
2162  05/12/2019  253.0  252.0  256.0  249.0   8784.0  53.41
2163  05/13/2019  254.0  255.0  257.0  252.0  11084.0  55.86
2164  05/14/2019  256.0  259.0  262.0  256.0  22409.0  58.96
2165  05/15/2019  260.0  258.0  263.0  258.0  50837.0  57.86
2166  05/16/2019  256.0  258.0  261.0  256.0  14328.0  57.86
2167  05/19/2019  258.0  258.0  259.0  255.0   6877.0  57.86
2168  05/20/2019  255.0  260.0  262.0  255.0  28735.0  59.73
2169  05/21/2019  260.0  259.0  262.0  257.0  24203.0  58.34
2170  05/22/2019  261.0  260.0  261.0  258.0  12840.0  59.36
2171  05/23/2019  262.0  258.0  262.0  257.0  12981.0  56.39
2172  05/26/2019  260.0  257.0  261.0  256.0   7119.0  54.91
2173  05/27/2019  253.0  254.0  256.0  253.0  20440.0  50.62
2174  05/28/2019  255.0  256.0  258.0  255.0   8158.0  53.24
2175  05/29/2019  256.0  258.0  261.0  256.0   5944.0  55.77
2176  05/30/2019  263.0  261.0  271.0  260.0  54518.0  59.32
2177  06/02/2019  256.0  257.0  261.0  256.0   9144.0  53.19
2178  06/03/2019  261.0  253.0  261.0  253.0  16404.0  47.86
2179  06/04/2019  254.0  253.0  258.0  253.0   7045.0  47.86
2180  06/06/2019  253.0  254.0  255.0  253.0   4723.0  49.33
2181  06/10/2019  255.0  254.0  255.0  254.0  10550.0  49.33
2182  06/11/2019  256.0  254.0  256.0  254.0   8195.0  49.33
2183  06/12/2019  256.0  254.0  256.0  253.0   3088.0  49.33
2184  06/13/2019  253.0  252.0  256.0  252.0  10387.0  45.85
2185  06/16/2019  252.0  250.0  255.0  250.0  14885.0  42.61
2186  06/17/2019  254.0  252.0  254.0  250.0  10325.0  46.67
2187  06/18/2019  250.0  253.0  254.0  250.0   8318.0  48.62
2188  06/19/2019  251.0  251.0  252.0  250.0  11715.0  45.06
2189  06/20/2019  251.0  251.0  253.0  250.0   5844.0  45.06

[2190 rows x 7 columns]

In [435]:
to_csv = df.to_csv (r'/home/deven/Desktop/file/_srbl.csv', index = None, header=True)